version: "3.8"

services:
  backend:
    build: ./idec_backend
    container_name: idec-backend
    ports:
      - "8082:8082"
    env_file:
      - ./idec_backend/.env
    restart: unless-stopped

  frontend:
    build: ./idec_frontend
    container_name: idec-frontend
    ports:
      - "8002:80"
    restart: unless-stopped
